
# получение объявлений
GET http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token 4cf59a51ba32addab5223a716694259d0c1ee477
###

# создание объявления
POST http://localhost:8000/api/advertisements/
Authorization: Token 4cf59a51ba32addab5223a716694259d0c1ee477
Content-Type: application/json

{
  "title": "Шкаф IKEA99",
  "description": "Срочно"
}

###

# поменять своё объявление
PATCH http://localhost:8000/api/advertisements/42/
Content-Type: application/json
Authorization: Token 4cf59a51ba32addab5223a716694259d0c1ee477

{
  "status": "OPEN"
}

###

# попытка поменять чужое объявление
PATCH http://localhost:8000/api/advertisements/7/
Content-Type: application/json
Authorization: Token a5844d9419c7816aa85976581c31d02b1bb35d32

{
  "status": "CLOSED",
  "draft": true
}

###

# попытка поменять чужое объявление (только статус)
PATCH http://localhost:8000/api/advertisements/42/
Content-Type: application/json
Authorization: Token a5844d9419c7816aa85976581c31d02b1bb35d32

{
  "status": "OPEN"
}

###

# Удаление своего объявления
DELETE http://localhost:8000/api/advertisements/42/
Authorization: Token 4cf59a51ba32addab5223a716694259d0c1ee477
###

# Неудачная попытка удаления чужого объявления юзером/успешное удаление админом чужого объявления
DELETE http://localhost:8000/api/advertisements/7/
Authorization: Token a5844d9419c7816aa85976581c31d02b1bb35d32
###

# фильтрация по создателю
GET http://localhost:8000/api/advertisements/?creator=7
Content-Type: application/json
###

# фильтрация по дате
GET http://localhost:8000/api/advertisements/?created_at_after=2022-12-23
###

# Добавление обявления в Избранное (номер в url-е это id объявления)
POST http://localhost:8000/api/advertisements/40/add_favorite/
Authorization: Token a5844d9419c7816aa85976581c31d02b1bb35d32
Content-Type: application/json
###

# получение своих Избранных объявлений
GET http://localhost:8000/api/advertisements/favorites/
Content-Type: application/json
Authorization: Token a5844d9419c7816aa85976581c31d02b1bb35d32
###

# Удаление записи(объявления) из своего Избранного
DELETE http://localhost:8000/api/advertisements/17/del_favorite/
Authorization: Token a5844d9419c7816aa85976581c31d02b1bb35d32
Content-Type: application/json
###