# Generated by Django 4.1.4 on 2022-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='draft_adv',
            field=models.IntegerField(default=0),
        ),
    ]
