# Generated by Django 4.1.4 on 2022-12-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_Tag_ArticleTag_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
