# Generated by Django 4.1.3 on 2022-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('price', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=15)),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
        ),
    ]
